#!/bin/bash
set -e
set -x
#./Debug+Asserts/bin/llvm-translate ../atomicc/examples/counter/counter.ll ../atomicc/examples/counter/atomicc.ll
#./Debug+Asserts/bin/llvm-translate ../atomicc/examples/echo/echo.exe.bc
catchsegv ./Debug+Asserts/bin/llvm-translate ../atomicc/examples/echo/echo.ll ../atomicc/examples/echo/atomicc.ll

#    gdb ./Debug+Asserts/bin/llvm-translate
